Several updates based on discussion
pulp/pups pull request #1
Opened 2017-03-16 20:39 UTC by bmbouter

* The name PUP is now used.
    * PUPs will live as pull requests until a decision is made.
    * A dedicated repo will now be used instead of pulpproject.org.
    * Voting uess a minimum of 12 days instead of 10.
    * The alternative of using Github for feedback is removed because
      feedback is now allowed directly on the pull request in addition to
      the mailing list.
    * The alternative of keeping PUPs as pull requests has been adopted and
      has been removed from the alternatives section.
    * Several minor grammer and wording edits.
    * A README.md was added

2017-03-21 15:02 UTC, daviddavis requested changes
Just some style problems I noticed.

2017-03-21 15:02 UTC, daviddavis commented on pup-0001.md
> +^^^^^^^^^^^^
I don't think upticks work in markdown.

2017-03-21 15:02 UTC, daviddavis commented on pup-0001.md
> +Note that votes can come from anyone, not just core devs [#f1]_. This is directly modeled after [the
This footnote link doesn't work in markdown. The underscore italicizes text.

2017-03-21 15:02 UTC, daviddavis commented on pup-0001.md
> +::
Not needed in markdown.

2017-03-21 15:03 UTC, seandst commented on pup-0001.md
> +^^^^^^^^^^^^
Indeed: https://github.com/bmbouter/pups/blob/f7ef0eec798962c30b1fc65053211310acf268f9/pup-0001.md

2017-03-21 20:43 UTC, bmbouter commented on pup-0001.md
> +^^^^^^^^^^^^
Fixed in next push and I'm proofreading the page myself too using the github markdown this time. Thank you.

2017-03-21 20:44 UTC, bmbouter commented on pup-0001.md
> +::
fixed in next push

2017-03-22 12:49 UTC, daviddavis approved these changes

2017-03-22 13:53 UTC, bmbouter commented
With two +1 votes via the mailing list after the required amount of time, I'm merging it as approved.

2017-03-22 13:53 UTC, merged

2017-03-22 14:18 UTC, bmbouter commented on pup-0001.md
> +Note that votes can come from anyone, not just core devs [#f1]_. This is directly modeled after [the
fixed in next push